# Add pytest options here
# https://docs.pytest.org/en/6.2.x/example/simple.html
# https://docs.pytest.org/en/6.2.x/reference.html#ini-options-ref
[pytest]
; usefixtures = job_application
addopts = -s